# Generated by Django 4.0.6 on 2024-08-07 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='recipi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipi_name', models.CharField(max_length=100)),
                ('recipi_desc', models.CharField(max_length=500)),
                ('recipi_img', models.ImageField(upload_to='receipe')),
            ],
        ),
    ]
