# Generated by Django 4.0.6 on 2024-08-06 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peaple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='people',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
